// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"CustomLogo","status":true,"description":"Shows RPG Maker and user logos at the start of the game.","parameters":{"logo1":"","logo1ImageName":"MadeWithMv","logo1Skippable":"true","logo1Coordinate":"","logo1X":"408","logo1Y":"312","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"Joseph_Core","status":true,"description":"(v.1.0) Core functions for Joseph's plugins.","parameters":{}},
{"name":"Joseph_EvBase","status":true,"description":"","parameters":{}},
{"name":"Joseph_EvHub","status":true,"description":"","parameters":{}},
{"name":"Joseph_MoveNPC","status":true,"description":"(v.2.0) Make NPCs move to specified coordinates (allowing cross-map movement and background updates)","parameters":{}},
{"name":"Joseph_SetPlan","status":true,"description":"在指定时间点触发自定义插件命令","parameters":{"TotalDuration":"360"}},
{"name":"Joseph_AITalk","status":true,"description":"(v.1.0) A plugin for user input and AI response, with an exit button and history feature.","parameters":{}},
{"name":"Joseph_Menu","status":true,"description":"","parameters":{}},
{"name":"Joseph_CutScene","status":true,"description":"简单的过场动画插件 v1.0","parameters":{}},
{"name":"Joseph_HeadName","status":true,"description":"在NPC头顶显示名字","parameters":{}}
];
